name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Create zip
      uses: thedoctor0/zip-release@master
      with:
        filename: SourceWithAssets.zip
        exclusions: '*.git*'
        
    - name: Create Release
      id: create_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GHA_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "SourceWithAssets.zip"
        files: |
          ./SourceWithAssets.zip
          
